### ISSUE TITLE
请问一个问题关于亚马逊商城切换区域爬取

### ISSUE THREAD

**Issue by heppytt** [dheerajjc34/IFB_Scrapy#1]
如果要做到区域爬取数据应该如何做？

**Comment by dheerajjc34** [comment]
您所说的地区是什么意思？

**Comment by heppytt** [comment]
> 您所说的地区是什么意思？

![image](https://user-images.githubusercontent.com/17058423/89860466-192bb300-dbd6-11ea-8fce-10bd51877eaa.png)
能选择指定qu区域爬

**Comment by dheerajjc34** [comment]
对于amazon.com，您只需更改以下内容
response.css
response.xpath

这将帮助您找到它 https://chrome.google.com/webstore/detail/selectorgadget/mhjhnkcfbdhnjickkkdbjoemdmbfginb?hl=en

这些视频对我有很大帮助，建议您一次 
https://www.youtube.com/watch?v=ve_0h4Y8nuI&list=RDCMUCirPbvoHzD78Lnyll6YYUpg&start_radio=1&t=1

**Comment by heppytt** [comment]
> https://chrome.google.com/webstore/detail/selectorgadget/mhjhnkcfbdhnjickkkdbjoemdmbfginb?hl=en

好的 我先看看
谢谢。
